export {default as Home} from './body/home/Home'
export {default as Courses} from './body/courses/Courses'
export {default as User} from './body/user/User'
export {default as Footer} from './footer/Footer'
export {default as Login} from './login_register/login/Login'
export {default as Signup} from './login_register/signup/Signup'
export {default as Loading} from './loading/Loading'